-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.chat_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  zip_code text NOT NULL,
  price numeric NOT NULL,
  bedrooms integer NOT NULL,
  bathrooms numeric NOT NULL,
  square_feet integer NOT NULL,
  property_type text NOT NULL CHECK (property_type = ANY (ARRAY['house'::text, 'condo'::text, 'apartment'::text, 'townhouse'::text])),
  listing_type text NOT NULL CHECK (listing_type = ANY (ARRAY['sale'::text, 'rent'::text])),
  image_url text NOT NULL,
  description text NOT NULL,
  features ARRAY DEFAULT '{}'::text[],
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  year_built integer NOT NULL,
  parking integer DEFAULT 0,
  is_new boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT properties_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pulled_properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  property_id character varying UNIQUE,
  title text NOT NULL,
  description text,
  property_type character varying,
  operation_type character varying,
  address text,
  neighborhood character varying,
  city character varying,
  state character varying,
  postal_code character varying,
  latitude numeric,
  longitude numeric,
  price numeric,
  currency character varying DEFAULT 'MXN'::character varying,
  price_per_m2 numeric,
  bedrooms integer,
  bathrooms integer,
  half_bathrooms integer,
  parking_spaces integer,
  total_area_m2 numeric,
  covered_area_m2 numeric,
  lot_size_m2 numeric,
  floor_number integer,
  total_floors integer,
  age_years integer,
  construction_year integer,
  features jsonb,
  amenities jsonb,
  main_image_url text,
  image_urls jsonb,
  virtual_tour_url text,
  video_url text,
  agent_name character varying,
  agent_phone character varying,
  agent_email character varying,
  agency_name character varying,
  status character varying DEFAULT 'active'::character varying,
  is_featured boolean DEFAULT false,
  is_premium boolean DEFAULT false,
  source_url text NOT NULL,
  scraped_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  page_number integer,
  listing_date date,
  has_pool boolean DEFAULT false,
  has_garden boolean DEFAULT false,
  has_elevator boolean DEFAULT false,
  has_balcony boolean DEFAULT false,
  has_terrace boolean DEFAULT false,
  has_gym boolean DEFAULT false,
  has_security boolean DEFAULT false,
  pet_friendly boolean DEFAULT false,
  furnished boolean DEFAULT false,
  search_vector tsvector DEFAULT to_tsvector('spanish'::regconfig, ((((((COALESCE(title, ''::text) || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || (COALESCE(neighborhood, ''::character varying))::text) || ' '::text) || (COALESCE(city, ''::character varying))::text)),
  gps_coordinates character varying,
  message_url text,
  CONSTRAINT pulled_properties_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scraping_errors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  session_id uuid,
  url text NOT NULL,
  error_type character varying,
  error_message text,
  retry_count integer DEFAULT 0,
  resolved boolean DEFAULT false,
  CONSTRAINT scraping_errors_pkey PRIMARY KEY (id),
  CONSTRAINT scraping_errors_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.scraping_sessions(id)
);
CREATE TABLE public.scraping_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  session_name character varying,
  base_url text NOT NULL,
  total_pages integer,
  pages_scraped integer DEFAULT 0,
  properties_found integer DEFAULT 0,
  properties_inserted integer DEFAULT 0,
  properties_updated integer DEFAULT 0,
  status character varying DEFAULT 'running'::character varying,
  error_message text,
  started_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  completed_at timestamp with time zone,
  filters_applied jsonb,
  CONSTRAINT scraping_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.todo_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  list_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  completed boolean DEFAULT false,
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT todo_items_pkey PRIMARY KEY (id),
  CONSTRAINT todo_items_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.todo_lists(id)
);
CREATE TABLE public.todo_lists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  created_by_ai boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT todo_lists_pkey PRIMARY KEY (id),
  CONSTRAINT todo_lists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  property_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT user_favorites_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT user_favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text,
  avatar_url text,
  phone text,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);